/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import DTO.*;
import DAO.*;
import BUS.*;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tranconghung
 */
public class BienBanKiemKeJFrame extends javax.swing.JFrame {
    private DefaultTableModel jtbBienBanKiemKemodel;
    private int idBienBanKiemKe;
    private BienBanKiemKe bbkkiUpdate = new BienBanKiemKe();
    private BienBanKiemKe bbkkDelete = new BienBanKiemKe();
    /**
     * Creates new form BienBanKiemKeJFrame
     */
    public BienBanKiemKeJFrame() {
        initComponents();
        initTable();
        loadTable();
    }
    public void initTable(){
        jtbBienBanKiemKemodel = new DefaultTableModel();
        jtbBienBanKiemKemodel.setColumnIdentifiers(new String[]{"ID","Mã nhân viên","Tên biên bản","Ngày lập","Số lượng tồn","Số lượng","Chênh lệch","Lý do"});
        jtbBienBanKiemKe.setModel(jtbBienBanKiemKemodel);
    }
    public void loadTable(){
        try {
            BienBanKiemKeBUS bienBanKiemKeBUS = new BienBanKiemKeBUS();
            List<BienBanKiemKe> list = bienBanKiemKeBUS.LoadBienBanKiemKe(WIDTH);
            jtbBienBanKiemKemodel.setRowCount(0);
            for(BienBanKiemKe bbkk : list){
                jtbBienBanKiemKemodel.addRow(new Object[]{
                    bbkk.getIdBienBan(),bbkk.getID(),bbkk.getTenBienBan(),bbkk.getNgayLap(),bbkk.getSoLuongTonKho(),bbkk.getSoLuongThuc(),bbkk.getChenhLech(),
                    bbkk.getLyDo()
                });
            }
            jtbBienBanKiemKemodel.fireTableDataChanged();
            idBienBanKiemKe = list.size()+1;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private boolean checkIdNhanvien() throws HeadlessException{
        StringBuilder bd = new StringBuilder();
        if(jtfIDnhanvien.getText().equals("")){
            bd.append("Mã nhân viên không được để tróng");
        }
        if(bd.length() > 0){
            JOptionPane.showMessageDialog(this, bd, "Cảnh báo", JOptionPane.ERROR_MESSAGE);
            jtfIDnhanvien.setBackground(Color.red);
            return true;
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbBienBanKiemKe = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtfIDnhanvien = new javax.swing.JTextField();
        btnShow = new javax.swing.JButton();
        jtfTenBB = new javax.swing.JTextField();
        jtfSlTonKho = new javax.swing.JTextField();
        jtfSLThucThe = new javax.swing.JTextField();
        jtfChenhLech = new javax.swing.JTextField();
        jtfLydo = new javax.swing.JTextField();
        jdtNgaylap = new com.toedter.calendar.JDateChooser();
        jtfTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtbBienBanKiemKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbBienBanKiemKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbBienBanKiemKeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbBienBanKiemKe);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản lý biên bản kiểm kê", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24), new java.awt.Color(204, 0, 204))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("ID Nhân viên lập");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Tên biên bản");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Ngày lập");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Số lượng tồn kho");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Số lượng thực thể");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Chênh lệch");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Lý do");

        btnShow.setText("...");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        jtfSLThucThe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfSLThucTheKeyPressed(evt);
            }
        });

        jtfLydo.setAlignmentX(2.0F);
        jtfLydo.setAlignmentY(2.0F);

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setText("Thêm");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setText("jButton4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfChenhLech, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfIDnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfTenBB, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTimKiem))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4))))
                    .addComponent(jtfSlTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfLydo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfSLThucThe, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdtNgaylap, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jtfIDnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnShow)
                            .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimKiem))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jtfTenBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jdtNgaylap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jtfSlTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jtfSLThucThe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jtfChenhLech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jtfLydo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)
                            .addComponent(jButton4))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(!checkIdNhanvien()){
            try {
                BienBanKiemKe bbkk = new BienBanKiemKe();
                bbkk.setIdBienBan(idBienBanKiemKe);
                bbkk.setID(Integer.parseInt(jtfIDnhanvien.getText()));
                bbkk.setTenBienBan(jtfTenBB.getText());
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String finddate =  sdf.format(jdtNgaylap.getDate()).toString();
                bbkk.setNgayLap(Date.valueOf(finddate));
                bbkk.setSoLuongTonKho(Integer.parseInt(jtfSlTonKho.getText()));
                bbkk.setSoLuongThuc(Integer.parseInt(jtfSLThucThe.getText()));
                bbkk.setChenhLech(Integer.parseInt(jtfChenhLech.getText()));
                bbkk.setLyDo(jtfLydo.getText());
                BienBanKiemKeBUS bbkkbus = new BienBanKiemKeBUS();
                if(bbkkbus.addBienBanKiemKe(bbkk) > 0){
                    JOptionPane.showMessageDialog(this, "Bạn đã thêm Biên bản kiểm kê thành công");
                    jtfIDnhanvien.setText("");
                    jtfTenBB.setText("");
                    jdtNgaylap.cleanup();
                    jtfSlTonKho.setText("");
                    jtfSLThucThe.setText("");
                    jtfChenhLech.setText("");
                    jtfLydo.setText("");
                    loadTable();
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Thêm biên bản kiểm kê thất bại");
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jtbBienBanKiemKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbBienBanKiemKeMouseClicked
        try {
            int row = jtbBienBanKiemKe.getSelectedRow();
            if(row >= 0){
                int id = (Integer)jtbBienBanKiemKe.getValueAt(row, 0);
                BienBanKiemKeBUS bbkkbus = new BienBanKiemKeBUS();
                BienBanKiemKe bbkk = bbkkbus.getBienBanKiemKe(id);
                
                bbkkiUpdate = bbkkbus.getBienBanKiemKe(id);
                bbkkDelete = bbkkbus.getBienBanKiemKe(id);
                if(bbkk != null){
                    jtfIDnhanvien.setText(String.valueOf(bbkk.getID()));
                    jtfTenBB.setText(bbkk.getTenBienBan());
                    jdtNgaylap.setDate(bbkk.getNgayLap());
                    jtfSlTonKho.setText(String.valueOf(bbkk.getSoLuongTonKho()));
                    jtfSLThucThe.setText(String.valueOf(bbkk.getSoLuongThuc()));
                    jtfChenhLech.setText(String.valueOf(bbkk.getChenhLech()));
                    jtfLydo.setText(bbkk.getLyDo());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage(),"Lối không lấy dữ liệu từ Table được.",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtbBienBanKiemKeMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            BienBanKiemKe bbkk = new BienBanKiemKe();
            bbkk = this.bbkkiUpdate;
            bbkk.setID(Integer.parseInt(jtfIDnhanvien.getText()));
            bbkk.setTenBienBan(jtfTenBB.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String finddate =  sdf.format(jdtNgaylap.getDate()).toString();
            bbkk.setNgayLap(Date.valueOf(finddate));
            bbkk.setSoLuongTonKho(Integer.parseInt(jtfSlTonKho.getText()));
            bbkk.setSoLuongThuc(Integer.parseInt(jtfSLThucThe.getText()));
            bbkk.setChenhLech(Integer.parseInt(jtfChenhLech.getText()));
            bbkk.setLyDo(jtfLydo.getText());
            if(JOptionPane.showConfirmDialog(this, "Bạn có muốn Update không?", "Hỏi"
            , JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION){
            return;
            }
            BienBanKiemKeBUS bbkkbus = new BienBanKiemKeBUS();
            if(bbkkbus.updateBienBanKiemKe(bbkk) > 0){
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                jtfIDnhanvien.setText("");
                jtfTenBB.setText("");
                jdtNgaylap.cleanup();
                jtfSlTonKho.setText("");
                jtfSLThucThe.setText("");
                jtfChenhLech.setText("");
                jtfLydo.setText("");
                loadTable();
            }
                
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Không cập nhật được", e.getMessage(),JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            if(JOptionPane.showConfirmDialog(this, "Bạn có có muốn xóa biên bản này không", "Hỏi"
            , JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION){
                return;
            }
            BienBanKiemKeBUS bbkkbus = new BienBanKiemKeBUS();
            if(bbkkbus.deleteBienBanKiemKe(bbkkDelete)){
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                loadTable();
            }
            else{
                JOptionPane.showMessageDialog(this,"Xóa thất bại");           
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jtfSLThucTheKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSLThucTheKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try {
                BienBanKiemKe bbkk = new BienBanKiemKe();
               
//                jtfSlTonKho.setText(""+bbkk.getSoLuongTonKho());
//                jtfSLThucThe.setText(""+bbkk.getSoLuongThuc());

                jtfChenhLech.setText(""+(Integer.parseInt(jtfSlTonKho.getText()) - Integer.parseInt(jtfSLThucThe.getText())));
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi");
            }
        }
    }//GEN-LAST:event_jtfSLThucTheKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BienBanKiemKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BienBanKiemKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BienBanKiemKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BienBanKiemKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BienBanKiemKeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdtNgaylap;
    private javax.swing.JTable jtbBienBanKiemKe;
    private javax.swing.JTextField jtfChenhLech;
    private javax.swing.JTextField jtfIDnhanvien;
    private javax.swing.JTextField jtfLydo;
    private javax.swing.JTextField jtfSLThucThe;
    private javax.swing.JTextField jtfSlTonKho;
    private javax.swing.JTextField jtfTenBB;
    private javax.swing.JTextField jtfTimKiem;
    // End of variables declaration//GEN-END:variables
}
