/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import DTO.NhanVien;
import DAO.*;
import BUS.*;
import java.beans.Customizer;
import java.sql.Date;
import java.util.*;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author tranconghung
 */
public class NhanVienJFrame extends javax.swing.JFrame {
    private DefaultTableModel jtbNhanVienmodel;
    private  NhanVienBUS nhanVienBUS = new NhanVienBUS();
    private NhanVien nhanVienUpdate = new NhanVien();
    private NhanVien nhanVienDelete = new NhanVien();
    private int nhanvienid;
    /**
     * Creates new form NhanVienJFrame
     */
    public NhanVienJFrame() {
        initComponents();
        initTable();
        loadData();
    }

    private void initTable(){
        jtbNhanVienmodel = new DefaultTableModel();
        jtbNhanVienmodel.setColumnIdentifiers(new String[] {"ID","Tên nhân viên","GioiTinh","NgaySinh","SoDienThoai","Email","DiaChi"});
        jtbNhanVien.setModel(jtbNhanVienmodel);
    }
    private void loadData(){
        try {
            NhanVienBUS nhanVienBUS = new NhanVienBUS();
            List<NhanVien> list  = nhanVienBUS.LoadNhanVien(WIDTH);
            jtbNhanVienmodel.setRowCount(0);
            for(NhanVien nv : list){
                jtbNhanVienmodel.addRow(new Object[]{
                    nv.getID(),nv.getTenNhanVien(),nv.getGioiTinh(),nv.getNgaySinh(),nv.getSoDienThoai(),nv.getEmail(),nv.getDiaChi()
                });
            }
            jtbNhanVienmodel.fireTableDataChanged();
            nhanvienid = list.size() + 1;
        } catch (Exception e) {
            e.printStackTrace();

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbNhanVien = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfHovaTenNhanvien = new javax.swing.JTextField();
        jtfGioitinhNhanvien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfSdtNhanvien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfEmailNhanvien = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfDiachiNhanvien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jdtNgaySinh = new com.toedter.calendar.JDateChooser();
        jtfTimkiem = new javax.swing.JTextField();
        btnTimkiem = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtbNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbNhanVien);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản lý nhân viên", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Họ và tên");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Giới tính");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Ngày sinh");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Số điện thoại");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Email");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Địa chỉ");

        jtfTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTimkiemActionPerformed(evt);
            }
        });
        jtfTimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTimkiemKeyReleased(evt);
            }
        });

        btnTimkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jtfSdtNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfHovaTenNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfEmailNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnSave)
                                        .addGap(57, 57, 57)
                                        .addComponent(btnUpdate)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnTimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(166, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfDiachiNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfGioitinhNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jtfHovaTenNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jdtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtfTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnTimkiem))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtfEmailNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfDiachiNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfSdtNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfGioitinhNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean Email(){
          String Email;
          Email = jtfEmailNhanvien.getText();
          String check = "^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$";
          if(!Email.matches(check)){
             return false;
          }else{
            return true;
          }
          
      }
    
    private void jtbNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbNhanVienMouseClicked
       try {
            int row = jtbNhanVien.getSelectedRow();
            if(row >= 0){
                int id = (Integer) jtbNhanVien.getValueAt(row, 0);
                NhanVienBUS nhanVienBUS = new NhanVienBUS();
                NhanVien nv = nhanVienBUS.getNhanVien(id);
                nhanVienUpdate = this.nhanVienBUS.getNhanVien(id);
                nhanVienDelete = this.nhanVienBUS.getNhanVien(id);
                if(nv != null){
                    jtfHovaTenNhanvien.setText(nv.getTenNhanVien());
                    jtfGioitinhNhanvien.setText(nv.getGioiTinh());
                    jdtNgaySinh.setDate(nv.getNgaySinh());
                    jtfSdtNhanvien.setText(nv.getSoDienThoai());
                    jtfEmailNhanvien.setText(nv.getEmail());
                    jtfDiachiNhanvien.setText(nv.getDiaChi());
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtbNhanVienMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(jtfHovaTenNhanvien.getText().isBlank() || jtfGioitinhNhanvien.getText().isBlank() || jdtNgaySinh.getDate()== null
            || jtfSdtNhanvien.getText().isBlank() || jtfEmailNhanvien.getText().isBlank() || jtfDiachiNhanvien.getText().isBlank()){
                JOptionPane.showMessageDialog(this, "Không được điền thiếu thông tin nhân viên");
                return;
            }         
            try {
                if(!Email()){
                    JOptionPane.showMessageDialog(this, "Sai ding dang Email");
                    return;
                }
                NhanVien nhanVien = new NhanVien();
                nhanVien.setID(nhanvienid);
                nhanVien.setTenNhanVien(jtfHovaTenNhanvien.getText());
                nhanVien.setGioiTinh(jtfGioitinhNhanvien.getText());
//                nhanVien.setNgaySinh(Date.valueOf(jtfNgaysinhNhanvien.getDate().toString()));
//                nhanVien.setNgaySinh(String.valueOf(jtfNgaysinhNhanvien.getText()));
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String finddate =  sdf.format(jdtNgaySinh.getDate()).toString();
                nhanVien.setNgaySinh( Date.valueOf(finddate));
                nhanVien.setSoDienThoai(jtfSdtNhanvien.getText());

                nhanVien.setEmail(jtfEmailNhanvien.getText());
                nhanVien.setDiaChi(jtfDiachiNhanvien.getText());
                NhanVienBUS nhanVienBUS = new NhanVienBUS();
                if(nhanVienBUS.saveNhanvien(nhanVien) > 0){
                    JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công");
                    jtfHovaTenNhanvien.setText("");
                    jtfGioitinhNhanvien.setText("");
                    //jdtNgaySinh.setDate("");
                    jdtNgaySinh.cleanup();
                    jtfSdtNhanvien.setText("");
                    jtfEmailNhanvien.setText("");
                    jtfDiachiNhanvien.setText("");
                    loadData();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Thêm nhân viên thất bại");
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Thêm nhân viên thất bại");
            }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            if(!Email()){
                    JOptionPane.showMessageDialog(this, "Sai ding dang Email");
                    return;
            }
            NhanVien nhanVien = new NhanVien();
            nhanVien = this.nhanVienUpdate;
            nhanVien.setTenNhanVien(jtfHovaTenNhanvien.getText());
            nhanVien.setGioiTinh(jtfGioitinhNhanvien.getText());
//            nhanVien.setNgaySinh(jtfNgaysinhNhanvien.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String finddate =  sdf.format(jdtNgaySinh.getDate()).toString();
            nhanVien.setNgaySinh( Date.valueOf(finddate));
            nhanVien.setSoDienThoai(jtfSdtNhanvien.getText()); 
            nhanVien.setEmail(jtfEmailNhanvien.getText());
            nhanVien.setDiaChi(jtfDiachiNhanvien.getText());
            
            if(JOptionPane.showConfirmDialog(this, "Bạn có muốn Update không?", "Hỏi"
            , JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION){
            return;
            }
            NhanVienBUS nhanVienBUS = new NhanVienBUS();
            if(nhanVienBUS.updateNhanvien(nhanVien)>0){
                JOptionPane.showMessageDialog(null, "Update thành công");
                jtfHovaTenNhanvien.setText("");
                jtfGioitinhNhanvien.setText("");
                jdtNgaySinh.cleanup();
                jtfSdtNhanvien.setText("");
                jtfEmailNhanvien.setText("");
                jtfDiachiNhanvien.setText("");
                loadData();    
            }
            else{
                JOptionPane.showMessageDialog(null, "Update thất bại");
            }
        } catch (Exception e) {
            Logger.getLogger(NhanVienJFrame.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            if(JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Hỏi"
            , JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION){
            return;
            }
            NhanVienBUS nhanVienBUS = new NhanVienBUS();
            if(nhanVienBUS.deleteNhanvien(nhanVienDelete)){
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                loadData();
            }
            else{
                JOptionPane.showMessageDialog(null, "Xóa thất bại");
            }
        } catch (Exception e) {
            Logger.getLogger(NhanVienJFrame.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jtfTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTimkiemActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        try {
            NhanVienBUS nhanVienBUS = new NhanVienBUS();
            List<NhanVien> list = nhanVienBUS.findNhanVien(jtfTimkiem.getText());
            
            if(list.isEmpty()){
                JOptionPane.showMessageDialog(this,"Nhân viên không tồn tại" , "Cảnh báo", JOptionPane.ERROR_MESSAGE);
            }
            else{
                for(NhanVien nv : list){
                    jtfHovaTenNhanvien.setText(nv.getTenNhanVien());
                    jtfGioitinhNhanvien.setText(nv.getGioiTinh());
//                    jtfNgaysinhNhanvien.setText(nv.getNgaySinh());
                    jdtNgaySinh.setDate(nv.getNgaySinh());
                    jtfSdtNhanvien.setText(nv.getSoDienThoai());
                    jtfEmailNhanvien.setText(nv.getEmail());
                    jtfDiachiNhanvien.setText(nv.getDiaChi());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Nhân viên không tồn tại" , "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void jtfTimkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTimkiemKeyReleased
         try {
            NhanVienBUS nhanVienBUS = new NhanVienBUS();
            List<NhanVien> list = nhanVienBUS.findNhanVien(jtfTimkiem.getText());
            initTable();
            for(NhanVien nhanVien : list){
                jtbNhanVienmodel.addRow(new Object[]{
                    nhanVien.getID(),nhanVien.getTenNhanVien(),nhanVien.getGioiTinh(),nhanVien.getNgaySinh(),nhanVien.getSoDienThoai(),
                    nhanVien.getEmail(),nhanVien.getDiaChi()
                });
            }
        } catch (Exception e) {
             e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Nhân viên không tồn tại" , "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtfTimkiemKeyReleased
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdtNgaySinh;
    private javax.swing.JTable jtbNhanVien;
    private javax.swing.JTextField jtfDiachiNhanvien;
    private javax.swing.JTextField jtfEmailNhanvien;
    private javax.swing.JTextField jtfGioitinhNhanvien;
    private javax.swing.JTextField jtfHovaTenNhanvien;
    private javax.swing.JTextField jtfSdtNhanvien;
    private javax.swing.JTextField jtfTimkiem;
    // End of variables declaration//GEN-END:variables
}
