/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import DTO.SanPham;
import BUS.*;
import DTO.LoaiSanPham;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.Date;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author tranconghung
 */
public class SanPhamJPanel extends javax.swing.JPanel {
    private DefaultTableModel jtbSanPhammodel;
    private  SanPhamBUS sanphamBUS = new SanPhamBUS();
    private SanPham sanphamUpdate = new SanPham();
    private SanPham sanphamDelete = new SanPham();
    private int idsanpham;
    String duongdanfile = null;
    String tenfile = null;
    String duongdandata = "C:\\Users\\admin\\GitHub\\QuanLyMayTinh\\src\\main\\java\\Asset\\";
    
    DecimalFormat DecimalFormat = new DecimalFormat("#");
    
    private DefaultTableModel jtbLoaiSanPhammodel;
    private  LoaiSanPhamBUS loaisanphamBUS = new LoaiSanPhamBUS();
    private LoaiSanPham loaisanphamUpdate = new LoaiSanPham();
    private LoaiSanPham loaisanphamDelete = new LoaiSanPham();
    private int idloaisanpham;
    /**
     * Creates new form SanPhamJPanel
     */
    public SanPhamJPanel() {
        initComponents();
        initTable();
        loadData();
        initTableLSP();
        loadDataLSP();
    }
    private void initTable(){
        jtbSanPhammodel = new DefaultTableModel();
        jtbSanPhammodel.setColumnIdentifiers(new String[] {"STT","Mã sản phẩm","Tên sản phẩm","Loại sản phẩm","Giá","Số lượng","Ngày sản xuất"});
        jtbSanPham.setModel(jtbSanPhammodel);
    }
    
    private void loadData(){
        try {
            SanPhamBUS sanphamBUS = new SanPhamBUS();
            List<SanPham> list  = sanphamBUS.LoadSanPham(WIDTH);
            jtbSanPhammodel.setRowCount(0);
            int i = 1;
            for(SanPham sp : list){
                jtbSanPhammodel.addRow(new Object[]{
                    i++,sp.getID(),sp.getTenSanPham(),sp.getIdLoaiSanPham(),DecimalFormat.format(sp.getGia()),sp.getSoLuong(),sp.getNgaySanXuat()});
            }
            jtbSanPhammodel.fireTableDataChanged();
            idsanpham = list.size() + 1;
        } catch (Exception e) {
            e.printStackTrace();

        }
    }
    public ImageIcon ResizeImage(String ImagePath){
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(150,150,Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    private void initTableLSP(){
        jtbLoaiSanPhammodel = new DefaultTableModel();
        jtbLoaiSanPhammodel.setColumnIdentifiers(new String[] {"ID","Tên loại sản phẩm"});
        jtbLoaiSanPham3.setModel(jtbLoaiSanPhammodel);
    }
    
    private void loadDataLSP(){
        try {
            LoaiSanPhamBUS loaisanphamBUS = new LoaiSanPhamBUS();
            List<LoaiSanPham> list  = loaisanphamBUS.LoadLoaiSanPham(WIDTH);
            jtbLoaiSanPhammodel.setRowCount(0);
            for(LoaiSanPham lsp : list){
                jtbLoaiSanPhammodel.addRow(new Object[]{
                    lsp.getID(),lsp.getTenLoaiSanPham()});
            }
            jtbLoaiSanPhammodel.fireTableDataChanged();
            idloaisanpham = list.size() + 1;
        } catch (Exception e) {
            e.printStackTrace();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jtfSoLuong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfTenSanPham = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfIdLoaiSanPham = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfGia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jpHinhAnh = new javax.swing.JPanel();
        lbimage = new javax.swing.JLabel();
        btnUpLoad = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jtfTimKiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jdtNgaySanXuat = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbSanPham = new javax.swing.JTable();
        jlbTenAnh = new javax.swing.JLabel();
        jlbDuongDanAnh = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jtfTenLoaiSanPham3 = new javax.swing.JTextField();
        btnSave4 = new javax.swing.JButton();
        btnUpdate4 = new javax.swing.JButton();
        btnDelete4 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtbLoaiSanPham3 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(983, 650));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản Phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24), new java.awt.Color(204, 0, 204))); // NOI18N

        jtfSoLuong.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSoLuongActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Số lượng");

        jtfTenSanPham.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfTenSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTenSanPhamActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tên sản phẩm");

        jtfIdLoaiSanPham.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Loại sản phẩm");

        jtfGia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfGiaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Giá");

        jpHinhAnh.setBackground(new java.awt.Color(255, 255, 255));
        jpHinhAnh.setForeground(new java.awt.Color(255, 51, 51));
        jpHinhAnh.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout jpHinhAnhLayout = new javax.swing.GroupLayout(jpHinhAnh);
        jpHinhAnh.setLayout(jpHinhAnhLayout);
        jpHinhAnhLayout.setHorizontalGroup(
            jpHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpHinhAnhLayout.createSequentialGroup()
                .addGap(0, 150, Short.MAX_VALUE)
                .addComponent(lbimage))
        );
        jpHinhAnhLayout.setVerticalGroup(
            jpHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpHinhAnhLayout.createSequentialGroup()
                .addGap(0, 150, Short.MAX_VALUE)
                .addComponent(lbimage))
        );

        btnUpLoad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpLoad.setText("Chọn  ảnh");
        btnUpLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpLoadActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\Image\\icons8-update-left-rotation-27.png"));
        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\Image\\icons8-delete-27.png"));
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\Image\\icons8-add-27.png"));
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\Image\\icons8-search-27.png"
        ));
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jtfTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTimKiemKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ngày lập");

        jdtNgaySanXuat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        jtbSanPham.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbSanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbSanPham);

        jlbTenAnh.setText("jLabel2");

        jlbDuongDanAnh.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdtNgaySanXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(jtfTenSanPham)
                    .addComponent(jtfIdLoaiSanPham)
                    .addComponent(jtfGia)
                    .addComponent(jtfSoLuong))
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jpHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbTenAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpLoad))
                        .addGap(39, 39, 39))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbDuongDanAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfTenSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfIdLoaiSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfGia, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdtNgaySanXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnUpLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbTenAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jlbDuongDanAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Sản Phẩm", jPanel2);

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Loại sản phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24), new java.awt.Color(204, 0, 204))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Tên Loại sản phẩm");

        jtfTenLoaiSanPham3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfTenLoaiSanPham3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTenLoaiSanPham3ActionPerformed(evt);
            }
        });

        btnSave4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave4.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\Image\\icons8-add-27.png"));
        btnSave4.setText("Lưu");
        btnSave4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave4ActionPerformed(evt);
            }
        });

        btnUpdate4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate4.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\Image\\icons8-update-left-rotation-27.png"));
        btnUpdate4.setText("Cập nhật");
        btnUpdate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate4ActionPerformed(evt);
            }
        });

        btnDelete4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete4.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\Image\\icons8-delete-27.png"));
        btnDelete4.setText("Xóa");
        btnDelete4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete4ActionPerformed(evt);
            }
        });

        jtbLoaiSanPham3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbLoaiSanPham3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbLoaiSanPham3MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jtbLoaiSanPham3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnSave4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtfTenLoaiSanPham3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfTenLoaiSanPham3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Loại Sản Phẩm", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSoLuongActionPerformed

    private void jtfTenSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTenSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTenSanPhamActionPerformed

    private void jtfGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfGiaActionPerformed

    private void btnUpLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpLoadActionPerformed
        try
        {

            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Mở thư mục");
            fileChooser.showOpenDialog(null);
            File ftenanh = fileChooser.getSelectedFile();
            duongdanfile = ftenanh.getParent();
            tenfile = ftenanh.getName();

            String duongdananh = duongdanfile + "\\" + tenfile;
            lbimage.setIcon(ResizeImage(String.valueOf(duongdananh)));
            jlbTenAnh.setText(tenfile);
            jlbDuongDanAnh.setText(duongdananh);
            System.out.println("duong dan anh la: " +duongdananh);
        }
        catch(Exception e)
        {
        }
    }//GEN-LAST:event_btnUpLoadActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            SanPham sanPham = new SanPham();
            sanPham = this.sanphamUpdate;
            sanPham.setTenSanPham(jtfTenSanPham.getText());
            sanPham.setIdLoaiSanPham(Integer.parseInt(jtfIdLoaiSanPham.getText()));
            sanPham.setGia(Integer.parseInt(jtfGia.getText()));
            sanPham.setSoLuong(Integer.parseInt(jtfSoLuong.getText()));
            sanPham.setMoTa(jTextArea.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String finddate =  sdf.format(jdtNgaySanXuat.getDate()).toString();
            sanPham.setNgaySanXuat( Date.valueOf(finddate));
            sanPham.setHinhAnh(jlbTenAnh.getText());

            if(JOptionPane.showConfirmDialog(this, "Bạn có muốn Update không?", "Hỏi"
                , JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION){
            return;
        }
        SanPhamBUS sanPhamBUS = new SanPhamBUS();
        if(sanPhamBUS.updateSanPham(sanPham) > 0){
            Files.copy(Paths.get(jlbDuongDanAnh.getText()), Paths.get(duongdandata + jlbTenAnh.getText()),StandardCopyOption.REPLACE_EXISTING);
            JOptionPane.showMessageDialog(null, "Update thành công");
            jtfTenSanPham.setText("");
            jtfIdLoaiSanPham.setText("");
            jdtNgaySanXuat.cleanup();
            jtfGia.setText("");
            jtfSoLuong.setText("");
            jTextArea.setText("");
            loadData();
        }

        else{
            JOptionPane.showMessageDialog(null, "Update thất bại");
        }
        } catch (Exception e) {
            Logger.getLogger(SanPhamJFrame.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            if(JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Hỏi"
                , JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION){
            return;
        }
        SanPhamBUS sanPhamBUS = new SanPhamBUS();
        if(sanPhamBUS.deleteSanPham(sanphamDelete)){
            JOptionPane.showMessageDialog(null, "Xóa thành công");
            loadData();
        }
        else{
            JOptionPane.showMessageDialog(null, "Xóa thất bại");
        }
        } catch (Exception e) {
            Logger.getLogger(SanPhamJFrame.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(jtfTenSanPham.getText().isBlank() || jtfIdLoaiSanPham.getText().isBlank() || jtfGia.getText()== null
            || jtfSoLuong.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Không được điền thiếu thông tin sản phẩm");
            return;
        }
        try {
            SanPham sanPham = new SanPham();
            sanPham.setID(idsanpham);
            sanPham.setTenSanPham(jtfTenSanPham.getText());
            sanPham.setIdLoaiSanPham(Integer.parseInt(jtfIdLoaiSanPham.getText()));
            sanPham.setGia(Integer.parseInt(jtfGia.getText()));
            sanPham.setSoLuong(Integer.parseInt(jtfSoLuong.getText()));
            sanPham.setMoTa(jTextArea.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String finddate =  sdf.format(jdtNgaySanXuat.getDate()).toString();
            sanPham.setNgaySanXuat( Date.valueOf(finddate));

            sanPham.setHinhAnh(jlbTenAnh.getText());

            SanPhamBUS sanPhamBUS = new SanPhamBUS();
            if(sanPhamBUS.saveSanPham(sanPham) > 0){
                Files.copy(Paths.get(jlbDuongDanAnh.getText()), Paths.get(duongdandata + jlbTenAnh.getText()),StandardCopyOption.REPLACE_EXISTING);
                JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công");
                jtfTenSanPham.setText("");
                jtfIdLoaiSanPham.setText("");
                jdtNgaySanXuat.cleanup();
                jtfGia.setText("");
                jtfSoLuong.setText("");
                jTextArea.setText("");
                loadData();
            }
            else{
                JOptionPane.showMessageDialog(this, "Thêm sản phẩm thất bại");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Thêm sản phẩm thất bại");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jtbSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbSanPhamMouseClicked
        try {
            int row = jtbSanPham.getSelectedRow();
            if(row >= 0){
                int id = (Integer) jtbSanPham.getValueAt(row, 1);
                SanPhamBUS sanphamBUS = new SanPhamBUS();
                SanPham sp = sanphamBUS.getSanPham(id);
                sanphamUpdate = this.sanphamBUS.getSanPham(id);
                sanphamDelete = this.sanphamBUS.getSanPham(id);
                if(sp != null){
                    jtfTenSanPham.setText(sp.getTenSanPham());
                    jtfIdLoaiSanPham.setText(String.valueOf(sp.getIdLoaiSanPham()));
                    jtfGia.setText(DecimalFormat.format(sp.getGia()));
                    jtfSoLuong.setText(String.valueOf(sp.getSoLuong()));
                    lbimage.setIcon(ResizeImage(String.valueOf(duongdandata+sp.getHinhAnh())));
                    System.out.println(duongdandata+sp.getHinhAnh());
                    jdtNgaySanXuat.setDate(sp.getNgaySanXuat());
                    jTextArea.setText(sp.getHinhAnh());
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtbSanPhamMouseClicked

    private void jtfTenLoaiSanPham3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTenLoaiSanPham3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTenLoaiSanPham3ActionPerformed

    private void btnSave4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave4ActionPerformed
        if(jtfTenLoaiSanPham3.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Không được điền thiếu thông tin loại sản phẩm");
            return;
        }
        try {
            LoaiSanPham loaiSanPham = new LoaiSanPham();
            loaiSanPham.setID(idloaisanpham);
            loaiSanPham.setTenLoaiSanPham(jtfTenLoaiSanPham3.getText());

            LoaiSanPhamBUS loaisanphamBUS = new LoaiSanPhamBUS();
            if(loaisanphamBUS.saveLoaiSanPham(loaiSanPham) > 0){
                JOptionPane.showMessageDialog(this, "Thêm loại sản phẩm thành công");
                jtfTenLoaiSanPham3.setText("");
                loadDataLSP();
            }
            else{
                JOptionPane.showMessageDialog(this, "Thêm loại sản phẩm thất bại");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Thêm  loại sản phẩm thất bại");
        }
    }//GEN-LAST:event_btnSave4ActionPerformed

    private void btnUpdate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate4ActionPerformed
        try {
            LoaiSanPham loaiSanPham = new LoaiSanPham();
            loaiSanPham = this.loaisanphamUpdate;
            loaiSanPham.setTenLoaiSanPham(jtfTenLoaiSanPham3.getText());

            if(JOptionPane.showConfirmDialog(this, "Bạn có muốn Update không?", "Hỏi"
                , JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION){
            return;
        }
        LoaiSanPhamBUS loaisanphamBUS = new LoaiSanPhamBUS();
        if(loaisanphamBUS.updateLoaiSanPham(loaiSanPham) > 0){
            JOptionPane.showMessageDialog(null, "Update thành công");
            jtfTenLoaiSanPham3.setText("");
            loadDataLSP();
        }

        else{
            JOptionPane.showMessageDialog(null, "Update thất bại");
        }
        } catch (Exception e) {
            Logger.getLogger(SanPhamJFrame.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnUpdate4ActionPerformed

    private void btnDelete4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete4ActionPerformed
        try {
            if(JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Hỏi"
                , JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION){
            return;
        }
        LoaiSanPhamBUS loaisanphamBUS = new LoaiSanPhamBUS();
        if(loaisanphamBUS.deleteLoaiSanPham(loaisanphamDelete)){
            JOptionPane.showMessageDialog(null, "Xóa thành công");
            loadData();
        }
        else{
            JOptionPane.showMessageDialog(null, "Xóa thất bại");
        }
        } catch (Exception e) {
            Logger.getLogger(SanPhamJFrame.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnDelete4ActionPerformed

    private void jtbLoaiSanPham3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbLoaiSanPham3MouseClicked
        try {
            int row = jtbLoaiSanPham3.getSelectedRow();
            if(row >= 0){
                int id = (Integer) jtbLoaiSanPham3.getValueAt(row, 0);
                LoaiSanPhamBUS loaisanphamBUS = new LoaiSanPhamBUS();
                LoaiSanPham lsp = loaisanphamBUS.getLoaiSanPham(id);
                loaisanphamUpdate = this.loaisanphamBUS.getLoaiSanPham(id);
                loaisanphamDelete = this.loaisanphamBUS.getLoaiSanPham(id);
                if(lsp != null){
                    jtfTenLoaiSanPham3.setText(lsp.getTenLoaiSanPham());
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtbLoaiSanPham3MouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        try {
            SanPhamBUS SanPhamBUS = new SanPhamBUS();
            List<SanPham> list = SanPhamBUS.findSanPham(jtfTimKiem.getText());
            initTable();
            for(SanPham sp : list){
                jtbSanPhammodel.addRow(new Object[]{
                    sp.getID(),sp.getTenSanPham(),sp.getIdLoaiSanPham(),DecimalFormat.format(sp.getGia()),sp.getSoLuong(),sp.getNgaySanXuat(),sp.getMoTa()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Sản phẩm không tồn tại" , "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void jtfTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTimKiemKeyReleased
        try {
            SanPhamBUS SanPhamBUS = new SanPhamBUS();
            List<SanPham> list = SanPhamBUS.findSanPham(jtfTimKiem.getText());
            initTable();
            for(SanPham sp : list){
                jtbSanPhammodel.addRow(new Object[]{
                    sp.getID(),sp.getTenSanPham(),sp.getIdLoaiSanPham(),DecimalFormat.format(sp.getGia()),sp.getSoLuong(),sp.getNgaySanXuat(),sp.getMoTa()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Sản phẩm không tồn tại" , "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtfTimKiemKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete4;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave4;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnUpLoad;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdate4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea;
    private com.toedter.calendar.JDateChooser jdtNgaySanXuat;
    private javax.swing.JLabel jlbDuongDanAnh;
    private javax.swing.JLabel jlbTenAnh;
    private javax.swing.JPanel jpHinhAnh;
    private javax.swing.JTable jtbLoaiSanPham3;
    private javax.swing.JTable jtbSanPham;
    private javax.swing.JTextField jtfGia;
    private javax.swing.JTextField jtfIdLoaiSanPham;
    private javax.swing.JTextField jtfSoLuong;
    private javax.swing.JTextField jtfTenLoaiSanPham3;
    private javax.swing.JTextField jtfTenSanPham;
    private javax.swing.JTextField jtfTimKiem;
    private javax.swing.JLabel lbimage;
    // End of variables declaration//GEN-END:variables
}
