/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import BUS.DonHangBanBUS;
import DTO.DonHangBan;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
/**
 *
 * @author tranconghung
 */
public class ThongKeDonHangBanJFrame extends javax.swing.JFrame {
    DefaultTableModel jtbThongKeModel;
    DonHangBanBUS donHangBanBUS = new DonHangBanBUS();
    /**
     * Creates new form ThongKeJFrame
     */
    public ThongKeDonHangBanJFrame() throws Exception {
        initComponents();
        LoadDataTable();
        TongDoanhThu();
        this.setLocationRelativeTo(null);
        setDataToChart(jpnDonHangBan);
        
    }
    private void LoadDataTable(){
        jtbThongKeModel = new DefaultTableModel();
        jtbThongKeModel.setColumnIdentifiers(new String[]{"Mã hóa đơn","Ngày Bán","Tổng tiền"});
        try {
            ArrayList<DonHangBan> donHangBans = donHangBanBUS.getHoaDonAll();
            initTable(donHangBans);
        } catch (Exception e) {
            e.printStackTrace();
        }
        jtbThongKeDHB.setModel(jtbThongKeModel);
    }
    private void initTable(ArrayList<DonHangBan> donHangBans){
        for(DonHangBan hd : donHangBans){
            jtbThongKeModel.addRow(new Object[]{hd.getID(),hd.getNgayLap(),hd.getTongTien()});
        }
    }
    private float TongDoanhThu(){
        float Tong = 0;
        try {
            ArrayList<DonHangBan> donHangBans = donHangBanBUS.getHoaDonAll();
            for(DonHangBan dhb : donHangBans){
                Tong += dhb.getTongTien();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        jlbDoanhThu.setText(Tong+"");
        return Tong;
    }
    private void setDataToChart(JPanel jpnDonHangBan) throws Exception{
        List<DonHangBan> donHangBans = (ArrayList<DonHangBan>) donHangBanBUS.getHoaDonAll();
        if(donHangBans != null){
            DefaultCategoryDataset dataset = new DefaultCategoryDataset();
            for(DonHangBan dhb : donHangBans){
                dataset.addValue(dhb.getTongTien(), "Doanh thu trong ngày bán được", dhb.getNgayLap());
            }
            
            JFreeChart chart = ChartFactory.createBarChart("Thống Kê Doanh Thu", "Thời Gian", "Doanh Thu (VND)", dataset);
            ChartPanel chartPanel = new ChartPanel(chart);
            chartPanel.setPreferredSize(new Dimension(jpnDonHangBan.getWidth(),450));
            jpnDonHangBan.removeAll();
            jpnDonHangBan.setLayout(new CardLayout());
            jpnDonHangBan.add(chartPanel);
            jpnDonHangBan.validate();
            jpnDonHangBan.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbThongKeDHB = new javax.swing.JTable();
        jpnDonHangBan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbDoanhThu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtbThongKeDHB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbThongKeDHB);

        javax.swing.GroupLayout jpnDonHangBanLayout = new javax.swing.GroupLayout(jpnDonHangBan);
        jpnDonHangBan.setLayout(jpnDonHangBanLayout);
        jpnDonHangBanLayout.setHorizontalGroup(
            jpnDonHangBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );
        jpnDonHangBanLayout.setVerticalGroup(
            jpnDonHangBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Tổng doanh thu:");

        jlbDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlbDoanhThu.setForeground(new java.awt.Color(0, 0, 255));
        jlbDoanhThu.setText("VND");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbDoanhThu))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnDonHangBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlbDoanhThu))
                .addGap(0, 151, Short.MAX_VALUE))
            .addComponent(jpnDonHangBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeDonHangBanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeDonHangBanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeDonHangBanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeDonHangBanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ThongKeDonHangBanJFrame().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ThongKeDonHangBanJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbDoanhThu;
    private javax.swing.JPanel jpnDonHangBan;
    private javax.swing.JTable jtbThongKeDHB;
    // End of variables declaration//GEN-END:variables
}
